// <auto-generated />
using System;
using CryptoBacktestingDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoBacktestingDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260620103106_AddAiChatLogs")]
    partial class AddAiChatLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BacktestStrategyIndicator", b =>
                {
                    b.Property<int>("IndicatorsId")
                        .HasColumnType("int");

                    b.Property<int>("StrategiesId")
                        .HasColumnType("int");

                    b.HasKey("IndicatorsId", "StrategiesId");

                    b.HasIndex("StrategiesId");

                    b.ToTable("BacktestStrategyIndicator");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.AiChatLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateKey")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DateKey");

                    b.ToTable("AiChatLogs");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("StrategyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacktestSessionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsWinningTrade")
                        .HasColumnType("bit");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TradeType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacktestSessionId");

                    b.ToTable("BacktestResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BacktestSessionId = 1,
                            Commission = 10m,
                            EntryPrice = 63000m,
                            EntryTime = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExitPrice = 65000m,
                            ExitTime = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWinningTrade = true,
                            Quantity = 0.1m,
                            TradeType = 0
                        },
                        new
                        {
                            Id = 2,
                            BacktestSessionId = 1,
                            Commission = 10m,
                            EntryPrice = 64500m,
                            EntryTime = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExitPrice = 64000m,
                            ExitTime = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWinningTrade = false,
                            Quantity = 0.1m,
                            TradeType = 0
                        });
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CryptoPairId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsOptimized")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StrategyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CryptoPairId");

                    b.HasIndex("StrategyId");

                    b.ToTable("BacktestSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CryptoPairId = 1,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalBalance = 12350m,
                            InitialBalance = 10000m,
                            IsOptimized = true,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StrategyId = 1
                        });
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InitialCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LookbackPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PositionSizePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StopLossPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TakeProfitPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TradeDirection")
                        .HasColumnType("int");

                    b.Property<decimal?>("TrailingStopPercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("BacktestStrategies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 20, 12, 31, 5, 737, DateTimeKind.Local).AddTicks(4195),
                            Description = "A simple RSI strategy",
                            InitialCapital = 10000m,
                            IsActive = true,
                            LookbackPeriod = 100,
                            Name = "RSI Strategy",
                            PositionSizePercent = 100m,
                            StopLossPercent = 5m,
                            TakeProfitPercent = 10m,
                            TradeDirection = 0
                        });
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.CandleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CryptoPairId")
                        .HasColumnType("int");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CryptoPairId");

                    b.ToTable("CandleData");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.CryptoPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CryptoPairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseAsset = "BTC",
                            CreatedAt = new DateTime(2026, 6, 20, 12, 31, 5, 737, DateTimeKind.Local).AddTicks(3763),
                            CurrentPrice = 60000m,
                            QuoteAsset = "USD",
                            Symbol = "BTC/USD"
                        },
                        new
                        {
                            Id = 2,
                            BaseAsset = "ETH",
                            CreatedAt = new DateTime(2026, 6, 20, 12, 31, 5, 737, DateTimeKind.Local).AddTicks(3769),
                            CurrentPrice = 2000m,
                            QuoteAsset = "USD",
                            Symbol = "ETH/USD"
                        });
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.Indicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Indicators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 20, 12, 31, 5, 737, DateTimeKind.Local).AddTicks(4098),
                            Description = "Relative Strength Index",
                            Name = "RSI",
                            Period = 14,
                            Threshold = 70m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 20, 12, 31, 5, 737, DateTimeKind.Local).AddTicks(4104),
                            Description = "Moving Average Convergence Divergence",
                            Name = "MACD",
                            Period = 12,
                            Threshold = 26m,
                            Type = 1
                        });
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.IndicatorComparison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacktestStrategyId")
                        .HasColumnType("int");

                    b.Property<int>("ComparisonType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndicatorAId")
                        .HasColumnType("int");

                    b.Property<int>("IndicatorBId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetSignal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacktestStrategyId");

                    b.HasIndex("IndicatorAId");

                    b.HasIndex("IndicatorBId");

                    b.ToTable("IndicatorComparisons");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.OptimizationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CompositeScore")
                        .HasColumnType("float");

                    b.Property<decimal>("MaxDrawdownPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OptimizationRunId")
                        .HasColumnType("int");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SharpeApprox")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("int");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OptimizationRunId");

                    b.ToTable("OptimizationResults");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.OptimizationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacktestSessionId")
                        .HasColumnType("int");

                    b.Property<double>("BestCompositeScore")
                        .HasColumnType("float");

                    b.Property<string>("BestParamsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompletedCombinations")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterGridJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RanAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCombinations")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacktestSessionId");

                    b.ToTable("OptimizationRuns");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BacktestStrategyIndicator", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.Indicator", null)
                        .WithMany()
                        .HasForeignKey("IndicatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.BacktestStrategy", null)
                        .WithMany()
                        .HasForeignKey("StrategiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.Attachment", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.BacktestStrategy", "Strategy")
                        .WithMany("Attachments")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestResult", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.BacktestSession", "BacktestSession")
                        .WithMany("Results")
                        .HasForeignKey("BacktestSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestSession");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestSession", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.CryptoPair", "CryptoPair")
                        .WithMany("BacktestSessions")
                        .HasForeignKey("CryptoPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.BacktestStrategy", "Strategy")
                        .WithMany("BacktestSessions")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoPair");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.CandleData", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.CryptoPair", "CryptoPair")
                        .WithMany("CandleDataHistory")
                        .HasForeignKey("CryptoPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoPair");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.IndicatorComparison", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.BacktestStrategy", "BacktestStrategy")
                        .WithMany("Comparisons")
                        .HasForeignKey("BacktestStrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.Indicator", "IndicatorA")
                        .WithMany()
                        .HasForeignKey("IndicatorAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.Indicator", "IndicatorB")
                        .WithMany()
                        .HasForeignKey("IndicatorBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacktestStrategy");

                    b.Navigation("IndicatorA");

                    b.Navigation("IndicatorB");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.OptimizationResult", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.OptimizationRun", "OptimizationRun")
                        .WithMany("Results")
                        .HasForeignKey("OptimizationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptimizationRun");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.OptimizationRun", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.BacktestSession", "BacktestSession")
                        .WithMany("OptimizationRuns")
                        .HasForeignKey("BacktestSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestSession");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoBacktestingDashboard.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestSession", b =>
                {
                    b.Navigation("OptimizationRuns");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestStrategy", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("BacktestSessions");

                    b.Navigation("Comparisons");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.CryptoPair", b =>
                {
                    b.Navigation("BacktestSessions");

                    b.Navigation("CandleDataHistory");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.OptimizationRun", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
