// <auto-generated />
using System;
using CryptoBacktestingDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoBacktestingDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260609000000_AddTradeDirectionToStrategy")]
    partial class AddTradeDirectionToStrategy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BacktestStrategyIndicator", b =>
                {
                    b.Property<int>("IndicatorsId")
                        .HasColumnType("int");

                    b.Property<int>("StrategiesId")
                        .HasColumnType("int");

                    b.HasKey("IndicatorsId", "StrategiesId");

                    b.HasIndex("StrategiesId");

                    b.ToTable("BacktestStrategyIndicator");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacktestSessionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsWinningTrade")
                        .HasColumnType("bit");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TradeType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacktestSessionId");

                    b.ToTable("BacktestResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BacktestSessionId = 1,
                            Commission = 10m,
                            EntryPrice = 63000m,
                            EntryTime = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExitPrice = 65000m,
                            ExitTime = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWinningTrade = true,
                            Quantity = 0.1m,
                            TradeType = 0
                        },
                        new
                        {
                            Id = 2,
                            BacktestSessionId = 1,
                            Commission = 10m,
                            EntryPrice = 64500m,
                            EntryTime = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExitPrice = 64000m,
                            ExitTime = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsWinningTrade = false,
                            Quantity = 0.1m,
                            TradeType = 0
                        });
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CryptoPairId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsOptimized")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StrategyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CryptoPairId");

                    b.HasIndex("StrategyId");

                    b.ToTable("BacktestSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CryptoPairId = 1,
                            EndDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExecutedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalBalance = 12350m,
                            InitialBalance = 10000m,
                            IsOptimized = true,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StrategyId = 1
                        });
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InitialCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LookbackPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PositionSizePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StopLossPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TakeProfitPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TradeDirection")
                        .HasColumnType("int");

                    b.Property<decimal?>("TrailingStopPercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("BacktestStrategies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 12, 40, 21, 830, DateTimeKind.Local).AddTicks(5983),
                            Description = "A simple RSI strategy",
                            InitialCapital = 10000m,
                            IsActive = true,
                            LookbackPeriod = 100,
                            Name = "RSI Strategy",
                            PositionSizePercent = 100m,
                            StopLossPercent = 5m,
                            TakeProfitPercent = 10m,
                            TradeDirection = 0
                        });
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.CandleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CryptoPairId")
                        .HasColumnType("int");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CryptoPairId");

                    b.ToTable("CandleData");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.CryptoPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("QuoteAsset")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CryptoPairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseAsset = "BTC",
                            CreatedAt = new DateTime(2026, 6, 8, 12, 40, 21, 830, DateTimeKind.Local).AddTicks(5817),
                            CurrentPrice = 60000m,
                            QuoteAsset = "USD",
                            Symbol = "BTC/USD"
                        },
                        new
                        {
                            Id = 2,
                            BaseAsset = "ETH",
                            CreatedAt = new DateTime(2026, 6, 8, 12, 40, 21, 830, DateTimeKind.Local).AddTicks(5822),
                            CurrentPrice = 2000m,
                            QuoteAsset = "USD",
                            Symbol = "ETH/USD"
                        });
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.Indicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Indicators");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 12, 40, 21, 830, DateTimeKind.Local).AddTicks(5953),
                            Description = "Relative Strength Index",
                            Name = "RSI",
                            Period = 14,
                            Threshold = 70m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 12, 40, 21, 830, DateTimeKind.Local).AddTicks(5956),
                            Description = "Moving Average Convergence Divergence",
                            Name = "MACD",
                            Period = 12,
                            Threshold = 26m,
                            Type = 1
                        });
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.IndicatorComparison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BacktestStrategyId")
                        .HasColumnType("int");

                    b.Property<int>("ComparisonType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndicatorAId")
                        .HasColumnType("int");

                    b.Property<int>("IndicatorBId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetSignal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BacktestStrategyId");

                    b.HasIndex("IndicatorAId");

                    b.HasIndex("IndicatorBId");

                    b.ToTable("IndicatorComparisons");
                });

            modelBuilder.Entity("BacktestStrategyIndicator", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.Indicator", null)
                        .WithMany()
                        .HasForeignKey("IndicatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.BacktestStrategy", null)
                        .WithMany()
                        .HasForeignKey("StrategiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestResult", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.BacktestSession", "BacktestSession")
                        .WithMany("Results")
                        .HasForeignKey("BacktestSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacktestSession");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestSession", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.CryptoPair", "CryptoPair")
                        .WithMany("BacktestSessions")
                        .HasForeignKey("CryptoPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.BacktestStrategy", "Strategy")
                        .WithMany("BacktestSessions")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoPair");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.CandleData", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.CryptoPair", "CryptoPair")
                        .WithMany("CandleDataHistory")
                        .HasForeignKey("CryptoPairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CryptoPair");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.IndicatorComparison", b =>
                {
                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.BacktestStrategy", "BacktestStrategy")
                        .WithMany("Comparisons")
                        .HasForeignKey("BacktestStrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.Indicator", "IndicatorA")
                        .WithMany()
                        .HasForeignKey("IndicatorAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoBacktestingDashboard.Models.Crypto.Indicator", "IndicatorB")
                        .WithMany()
                        .HasForeignKey("IndicatorBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacktestStrategy");

                    b.Navigation("IndicatorA");

                    b.Navigation("IndicatorB");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestSession", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.BacktestStrategy", b =>
                {
                    b.Navigation("BacktestSessions");

                    b.Navigation("Comparisons");
                });

            modelBuilder.Entity("CryptoBacktestingDashboard.Models.Crypto.CryptoPair", b =>
                {
                    b.Navigation("BacktestSessions");

                    b.Navigation("CandleDataHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
